name: Build and Push Custom Codespace Image

on:
  push:
    branches:
      - main
      - develop
    paths:
      - "Dockerfile"
      - ".github/workflows/build_and_push_codespace.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU (for multi-arch builds)
        uses: docker/setup-qemu-action@v3.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.6.1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PERSONAL_TOKEN }}

      - name: Build and Push Custom Codespace Image
        uses: docker/build-push-action@v6.5.0
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/wkarts/chatwoot/custom-codespace:latest
            ghcr.io/wkarts/chatwoot/custom-codespace:${{ github.sha }}
