# This action will publish Chatwoot CE docker image.
# This is set to run against merges to develop, master
# and when tags are created.

name: Publish Chatwoot CE docker images for AMD64

on:
  push:
    branches:
      - develop
      - master
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: wkarts/hub
      GIT_REF: ${{ github.head_ref || github.ref_name }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies with Yarn
        run: |
          yarn config set cache-folder $(pwd)/.yarn-cache
          yarn install --modules-folder $(pwd)/.yarn-cache --silent --ignore-engines --ignore-scripts

      - name: Set up Docker tags
        id: docker_tag
        run: |
          echo "TAGS=${IMAGE_NAME}:${GIT_REF}" >> $GITHUB_ENV
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            echo "LATEST_TAG=${IMAGE_NAME}:latest" >> $GITHUB_ENV
          fi

      - name: Login to DockerHub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push amd64 image
        uses: docker/build-push-action@v6.5.0
        with:
          context: .
          file: docker/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.TAGS }}
            ${{ env.LATEST_TAG }}
