name: Publish Codespace Base ARM Image

on:
  workflow_dispatch:

jobs:
  publish-code-space-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.PERSONAL_TOKEN }}

    - name: Build the Codespace Base ARM Image 
      run: |
        docker-compose -f .devcontainer/docker-arm-compose.yml build base
        docker tag base:latest ghcr.io/wkarts/hub_arm_codespace:latest
        docker push ghcr.io/wkarts/hub_arm_codespace:latest
