name: Run Chatwoot CE spec
on:
  push:
    branches:
      - develop
      - master
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: postgres
        ports:
          - 5433:5432
        options: >-
          --mount type=tmpfs,destination=/var/lib/postgresql/data
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis
        ports:
          - 6380:6379
        options: --entrypoint redis-server

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        repository: ${{ github.event.pull_request.head.repo.full_name }}

    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: yarn

    - name: yarn
      run: yarn install

    - name: Create database
      env:
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      run: bundle exec rake db:create

    - name: Seed database
      env:
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      run: bundle exec rake db:schema:load

    - name: yarn check-files
      run: yarn install --check-files

    - name: Run backend tests
      env:
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        NODE_OPTIONS: --openssl-legacy-provider
      run: |
        bundle exec rspec --profile=10 --format documentation

    - name: Upload rails log folder
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: rails-log-folder
        path: log