name: Run Size Limit Check

on:
  pull_request:
    branches:
      - develop-internal-chat

jobs:
  test:
    #runs-on: ubuntu-20.04
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: yarn
        run: yarn install

      - name: Run asset compile
        run: bundle exec rake assets:precompile
        env:
          NODE_OPTIONS: --openssl-legacy-provider

      - name: Size Check
        run: yarn run size
